import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Peter',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'John@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Men's beach shirt",
      slug: 'mens-beach-shirt',
      category: 'Shirts',
      image: "/images/Men's-beach-shirt.jpg",
      price: 5500,
      brand: 'Ebano',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/shirt-banner.png',
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/Fit-shirt.jpg',
      price: 9000,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 18,
      countInStock: 57,
      description: 'A fashionable shirt',
      isFeatured: false,
      banner: '/images/shirt-banner.png',
    },
    {
      name: 'baggy Jeans',
      slug: 'baggy-Jeans',
      category: 'Jeans',
      image: '/images/baggy-Jeans.jpg',
      price: 1000,
      brand: 'Defacto',
      rating: 4.2,
      numReviews: 13,
      countInStock: 34,
      description: 'A baggy jeans',
      isFeatured: true,
      banner: '/images/jeans-banner.png',
    },
    {
      name: 'fitted Jeans',
      slug: 'fitted-Jeans',
      category: 'Jeans',
      image: '/images/fitted-Jeans.jpg',
      price: 18000,
      brand: 'Defacto',
      rating: 4.4,
      numReviews: 33,
      countInStock: 4,
      description: 'A fit jeans',
      isFeatured: true,
      banner: '/images/jeans-banner.png',
    },
    {
      name: 'ripped Jeans',
      slug: 'ripped-Jeans',
      category: 'Jeans',
      image: '/images/ripped-Jeans.jpg',
      price: 12000,
      brand: 'Versace',
      rating: 3.8,
      numReviews: 8,
      countInStock: 29,
      description: 'A pair of ripped jeans',
      isFeatured: false,
      banner: '/images/jeans-banner.png',
    },
    {
      name: "Men's Shoe",
      slug: 'shoe1',
      category: 'Shoe',
      image: '/images/shoe1.jpg',
      price: 55000,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 10,
      countInStock: 87,
      description: 'Men Glossy Tassel Brogue Leather Shoes ',
      isFeatured: true,
      banner: '/images/shoe-banner.png',
    },
  ],
};

export default data;
